### ISSUE TITLE
Package not working  

### ISSUE THREAD

**Issue by rajasekar-mu** [SheetJS/sheet.js.org#3]
Hi, 
I tried this repository, but its throw error failed to compiled. Upgraded react & react data grid as well, but not works.
```
./node_modules/react-data-grid/lib/bundle.js 104:16
Module parse failed: Unexpected token (104:16)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
```

Kindly share any specific version required?

Thanks. 

![image](https://user-images.githubusercontent.com/12061783/182760044-5e320c7c-b4f4-4f3c-b1f3-c6a3a4dacfb4.png)

**Comment by SheetJSDev** [comment]
From scratch:

1) switch to node v16.16.0 (v18 has errors).  You can use `n` for this:

```bash
sudo npm i -g n
sudo n 16
```

2) manually remove every `^` in the `package.json` file

3) install with `npm i --force`

4) run `npm run build` to build the package or `npm start` for dev.

**Comment by rajasekar-mu** [comment]
react-data-grid latest beta patch version [7.0.0-beta.14](https://www.npmjs.com/package/react-data-grid/v/7.0.0-beta.14)  have issues, so downgraded to lower 

> react-data-grid@7.0.0-beta.11 

now its working, Thanks @SheetJSDev
